---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: helm-controller
  labels:
    app.kubernetes.io/name: helm-controller
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

subjects:
  - kind: ServiceAccount
    name: helm-controller

...
