---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: helm-controller
  labels:
    app.kubernetes.io/name: helm-controller
    app.kubernetes.io/component: controller

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: helm-controller
      app.kubernetes.io/component: controller

  template:
    metadata:
      labels:
        app.kubernetes.io/name: helm-controller
        app.kubernetes.io/component: controller

    spec:
      enableServiceLinks: false
      serviceAccountName: helm-controller

      containers:
        - name: server
          image: helm-controller
          imagePullPolicy: IfNotPresent

          command:
            - helm-controller

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi

...
